[tool.kedro]
package_name = "__projectSnake__"
project_name = "__nameDisplay__"
# this is the kedro version
project_version = "0.18.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = "kedro"
profile = "black"

# Disabled because it does not work togehter with the python debugger
#[tool.pytest.ini_options]
#addopts = """
#--cov-report term-missing \
#--cov src/__projectSnake__ -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
