version: '2.1'

services:           
    frontend:
        image: registry.craftworks.io/__nameKebab__/frontend:${IMAGE_VERSION}
        environment:
            - TZ=Europe/Vienna
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.port=80"
            - "traefik.frontend.rule=Host:${PR_PREFIX}{{ domain }}"
{% if basic_auth_enabled is defined and basic_auth_enabled == true %}                   
            - "traefik.frontend.auth.basic.usersFile=/htpasswd/{{ domain }}.htpasswd"
{% endif %}
            - craftworks.project.folder={{ project_path }}
            - craftworks.project.pr=${PR_PREFIX}
        mem_limit: 300m
        networks:
          - __nameKebab__-net
          - revproxy

    db:
        image: postgres:15
        volumes:
            - ./storage/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=__nameLower__
            - POSTGRES_USER=__nameLower__
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - PGDATA=/var/lib/postgresql/data/pgdata
            - TZ=Europe/Vienna
            - PGTZ=Europe/Vienna
{% if (db_external_port_template is defined) and (db_external_port_template is not none) and (db_external_port_template != 'None') %}
        ports:
            - {{ db_external_port_template }}:5432
{% endif %}
        networks:
            - __nameKebab__-net
        mem_limit: 300m
        restart: unless-stopped
        labels:
            - craftworks.project.folder={{ project_path }}
            - craftworks.project.pr=${PR_PREFIX}

    backend:
        image: registry.craftworks.io/__nameKebab__/backend:${IMAGE_VERSION}
        volumes:
            - ./logs:/app/logs
            - ./conf:/app/conf
        environment:
            - SPRING_CONFIG_ADDITIONAL_LOCATION=file:./conf/__nameKebab__.properties
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/__nameLower__
            - SPRING_DATASOURCE_USERNAME=__nameLower__
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
            - TZ=Europe/Vienna
        labels:
            - "traefik.enable=true"
            - "traefik.port=8080"
            - "traefik.app.frontend.rule=Host:${PR_PREFIX}{{ domain }};PathPrefix:/api/"
{% if basic_auth_enabled is defined and basic_auth_enabled == true %}            
            - "traefik.app.frontend.auth.basic.usersFile=/htpasswd/{{ domain }}.htpasswd"
{% endif %}
{% if swagger_exposed is defined and swagger_exposed == true %}
            - "traefik.swagger.frontend.rule=Host:${PR_PREFIX}{{ domain }};PathPrefix:/v3/api-docs"
            - "traefik.swagger.frontend.auth.basic.usersFile=/htpasswd/{{ domain }}.htpasswd"
{% endif %}
            - craftworks.project.folder={{ project_path }}
            - craftworks.project.pr=${PR_PREFIX}
        networks:
            - __nameKebab__-net
            - revproxy
        mem_limit: 800m
        restart: unless-stopped
        depends_on:
            - db

networks:
    revproxy:
        external: true
    __nameKebab__-net:
        driver: bridge
