version: 2

updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/lukas-test-frontend"
    schedule:
      interval: "monthly"
      time: "22:00"
      timezone: "Europe/Vienna"
    versioning-strategy: lockfile-only

  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "monthly"
      time: "22:00"
      timezone: "Europe/Vienna"
    versioning-strategy: lockfile-only

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "22:00"
      timezone: "Europe/Vienna"
    ignore:
      # we cannot update to spring boot 3.x so easily
      - dependency-name: "org.springframework.boot:*"
        versions: ["[3.0.0,)"]


  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/lukas-test-backend"
    schedule:
      interval: "monthly"
      time: "22:00"
      timezone: "Europe/Vienna"

  - package-ecosystem: "docker"
    directory: "/lukas-test-frontend"
    schedule:
      interval: "monthly"
      time: "22:00"
      timezone: "Europe/Vienna"

  - package-ecosystem: "docker"
    directory: "/e2e"
    schedule:
      interval: "monthly"
      time: "22:00"
      timezone: "Europe/Vienna"
    ignore:
      # even-numbered node releases are LTS
      - dependency-name: "cypress/base"
        versions: ["17.x", "19.x", "21.x", "23.x"]

  - package-ecosystem: "docker"
    directory: "/revproxy"
    schedule:
      interval: "monthly"
      time: "22:00"
      timezone: "Europe/Vienna"

  # Maintain dependencies for github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "22:00"
      timezone: "Europe/Vienna"
