version: '3'

## Adds an e2e service and setups other services for e2e tests
# Use docker-compose.yml as base
# e.g. `docker-compose -f docker-compose.yml -f docker-compose.e2e.yml up`

# Adjust the memory limits if necessary, but try to keep the limits low.

services:
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=e2e

  e2e:
    build: ./e2e
    depends_on:
      - revproxy
    environment:
      - WAIT_HOSTS=db:5432, backend:8080, frontend:80
      - CYPRESS_baseUrl=http://revproxy:80
      - TZ=Europe/Vienna
    mem_limit: 2048m