version: '3'

## Adds an e2e service and setups other services for e2e tests
# Use docker-compose.yml as base
# e.g. `docker-compose -f docker-compose.yml -f docker-compose.e2e.yml up`

# Adjust the memory limits if necessary, but try to keep the limits low.

services:
  # ===marker:start:backend===
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=e2e
  # ===marker:end:backend===

  e2e:
    build: ./e2e
    depends_on:
      - revproxy
    environment:
      - WAIT_HOSTS====marker:inline:start:backend===db:5432, backend:8080, ===marker:inline:end:backend======marker:inline:start:frontend===frontend:80===marker:inline:end:frontend===
      - CYPRESS_baseUrl=http://revproxy:80
      - TZ=Europe/Vienna
    mem_limit: 2048m