version: '3'

## Runs all services of the application
# See docker-compose.override.yml for exposed ports and mounted volumes

# Note:
# Since this docker-compose can be used to run on the build server:
# * Do not expose any ports
# * Do not mount any volumes

# Adjust the memory limits if necessary, but try to keep the limits low.

services:
    db:
        image: postgres:15
        environment:
            - POSTGRES_PASSWORD=lukastest
            - POSTGRES_USER=lukastest
            - POSTGRES_DB=lukastest
            - PGDATA=/var/lib/postgresql/data/pgdata
            - TZ=Europe/Vienna
            - PGTZ=Europe/Vienna
        mem_limit: 300m

    backend:
        image: registry.craftworks.io/lukas-test/backend:latest
        depends_on:
            - db
        environment:
            - SPRING_PROFILES_ACTIVE=dev,testdata
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lukastest
            - SPRING_DATASOURCE_USERNAME=lukastest
            - SPRING_DATASOURCE_PASSWORD=lukastest
            - TZ=Europe/Vienna
        mem_limit: 1024m

    frontend:
        image: registry.craftworks.io/lukas-test/frontend:latest
        environment:
            - TZ=Europe/Vienna
        depends_on:
            - backend
        mem_limit: 256m

    revproxy:
        build: revproxy
        environment:
            - TZ=Europe/Vienna
        depends_on:
            - backend
            - frontend
        mem_limit: 256m
