version: '3'

## Exposes ports of all services so that application is accessible via localhost[:80]
# For easier debugging, services are accessible via exposed ports

services:
    db:
        ports:
            - "127.0.0.1:5432:5432"

    backend:
        volumes:
            - ./logs:/app/logs
            - ./conf:/app/conf
        ports:
            - "127.0.0.1:8080:8080"

    frontend:
        ports:
            - "127.0.0.1:4200:80"

    revproxy:
        ports:
            - "127.0.0.1:80:80"