apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-backend-app-props'
  labels:
    app: '{{ .Release.Name }}-backend-app-props'
data:
  application.properties: |
    spring.profiles.active=prod