apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name }}-db-config
data:
  POSTGRES_URL: jdbc:postgresql://{{ .Release.Name }}-db:5432/lukastest
  POSTGRES_DB: lukastest
  POSTGRES_USER: lukastest
  POSTGRES_PASSWORD: lukastest
