- name: Creates parent directories
  file:
    path: '{{ item }}'
    state: directory
    owner: craftworks
    group: deploy
    mode: 0770
  with_items: 
    - '{{ project_path }}'
  become: yes


- name: Ensure directory structure exists
  file:
    path: '{{ project_path }}/{{ item.path }}'
    state: directory
    owner: craftworks
    group: deploy
    mode: 0770
  with_filetree: '../templates'
  when: item.state == 'directory'
  become: yes

- name: Ensure files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '{{ project_path }}/{{ item.path }}'
    owner: craftworks
    group: deploy
    mode: 0770
  with_filetree: '../templates'
  when: item.state == 'file'
  become: yes
  vars:
      db_external_port_template: "{{db_external_port | default('None')}}"

- name: Ensure directory for prs exists
  file:
    path: '{{ project_path }}/prs'
    state: directory
    owner: craftworks
    group: deploy
    mode: 0770

- name: Create pr docker-compose.yml
  template:
    src: 'docker-compose.yml'
    dest: '{{ project_path }}/prs/docker-compose.yml'
    owner: root
    group: root
    mode: 0644
  become: yes
    
- name: Create htpasswd file
  when: basic_auth_enabled | bool == true or swagger_exposed | bool == true
  htpasswd:
    path: /root/revproxy/htpasswd/{{ domain }}.htpasswd
    name: __nameLower__
    password: '{{ basic_auth_password }}'
    state: present
    owner: root
    group: root
    mode: 0644
  become: yes

# execute compose down + up 
- name: docker pull / down / update
  shell: 'cd {{ project_path }} && docker-compose pull && docker-compose down && docker-compose up -d'
  become: yes
